### ISSUE TITLE
The non-English path of the title appears garbled (recode)

### ISSUE THREAD

**Issue by aoaim** [tquin/hugo-tquin#60]
Hello! I'm planning to migrate my blog to hugo, so I'm looking for nice themes. I found "hugo-theme-console", a very nice and clean theme with a geeky look. I really like this theme, but it seems that the original author of this theme is no longer maintaining it, so there are some problems in using it. I found your answer in the original repository issues, which helped me solve some css related problems, thank you very much.

Since I am from China, I inevitably use Chinese in my blog. So I encountered a very serious problem, when my path contains Chinese, the header of the site appears garbled, it seems that the Chinese is transcoded into the code. If possible, could I ask you how to solve this problem? Thanks!

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/48897696/214252182-42a8828f-4f7a-4d24-af14-9830a4c9f050.png">

**Comment by tquin** [comment]
Hey, unfortunately I'm not an expert on Hugo, so I'm not sure exactly how to fix this. There doesn't seem to be any `url_decode` functionality that I could find from a quick Google search through the docs. I can tell you at least that the breadcrumb trail is generated in the `layouts/_default/baseof.html` file if you want to try and mess around with it.

```
<div class="logo terminal-prompt">
              {{ $url := replace .Permalink ( printf "%s" .Site.BaseURL) "" }}
              {{ $.Scratch.Add "path" .Site.BaseURL }}
              <a href="{{ .Site.BaseURL }}" class="no-style {{ with .Site.Params.TitleCutting }}site-name{{ end }}">{{ .Site.Title }}</a>:~# 
              {{ range $index, $element := split $url "/" }}{{ $.Scratch.Add "path" $element }}{{ if ne $element "" }}<a href='{{ $.Scratch.Get "path" | absURL }}'>{{ . }}</a>/{{ $.Scratch.Add "path" "/" }}{{ end }}{{ end }}</div>
```

There's some similar discussion here: https://discourse.gohugo.io/t/how-decode-urls-in-hugo/7549/4, but I wasn't able to get it to work. You might have a better chance posting your question on the [Hugo subreddit](https://www.reddit.com/r/gohugo/) or the [Hugo support forum](https://discourse.gohugo.io/c/support/34). Best of luck!
